channels:
  - conda-forge
dependencies:
  - python==3.5
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - numpy
  - scipy
  - matplotlib
  - astropy
  - six
  - emcee
  - corner
  - pip:
    - nbsphinx
    - astropy-sphinx-theme
