channels:
  - conda-forge
dependencies:
  - python==3.7
  - pip:
    - nbsphinx
    - astropy-sphinx-theme
    - sphinx>=1.7
    - pandoc
    - nbconvert
    - ipykernel
    - matplotlib
    - scipy

