name: General Issue
description: Your issue does not fit the categories already mentioned.
title: " "
labels: 
  - help wanted
body:
  - type: markdown
    attributes:
      value: >
        If you want to discuss more about the issue, reach us at our [Slack Channel](https://stingraysoftware.slack.com/ssb/redirect)
  - type: textarea
    attributes:
      label: Description of the Issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Your suggestions for the Fix
