channels:
  - conda-forge
dependencies:
  - python==3.5
  - sphinx>=1.4
  - pandoc
  - nbconvert
  - ipykernel
  - pip:
    - nbsphinx

requirements_file: requirements/docs.txt

python:
   setup_py_install: true

