name: CI Tests

on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    # run every Monday at 6am UTC
    - cron: '0 6 * * 1'

env:
  SETUP_XVFB: True  # avoid issues if mpl tries to open a GUI window
  TOXARGS: '-v'

jobs:
  ci-tests:
    name: ${{ matrix.os }}, ${{ matrix.tox_env }}
    runs-on: ${{ matrix.os }}
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[ci skip]'))"
    strategy:
      fail-fast: false
      matrix:
        # We're going to run the folowing to test basic functionality on all
        # supported versions of Python:
        #
        #   pyNNN-test on ubuntu-latest for all supported versions of Python (3.6+)
        #
        # Then we run specific tests only on the latest version (3.10 at time
        # of writing):
        #
        #   py310-test on windows-latest and macos-latest
        #   py310-test-cov on ubuntu-latest
        #   py310-test-astropy40 on ubuntu-latest
        #   py310-test-astropy50 on ubuntu-latest
        #   build_docs on Python 3.10 on ubuntu-latest
        #
        # The following are tested on Python 3.9, as 3.10 is known not to work
        # at time of writing:
        #
        #   py39-test-alldeps-cov on ubuntu-latest
        #   py39-test-astropy30 on ubuntu-latest


        include:
          - os: ubuntu-latest
            python: '3.6'
            tox_env: 'py36-test'
          - os: ubuntu-latest
            python: '3.7'
            tox_env: 'py37-test'
          - os: ubuntu-latest
            python: '3.8'
            tox_env: 'py38-test'
          - os: ubuntu-latest
            python: '3.9'
            tox_env: 'py39-test'
          - os: ubuntu-latest
            python: '3.10'
            tox_env: 'py310-test'
          - os: macos-latest
            python: '3.10'
            tox_env: 'py310-test'
          - os: windows-latest
            python: '3.10'
            tox_env: 'py310-test'
          - os: ubuntu-latest
            python: '3.10'
            tox_env: 'py310-test-cov'
          - os: ubuntu-latest
            python: '3.9'
            tox_env: 'py39-test-alldeps-cov'
            use_remote_data: true
          - os: ubuntu-latest
            python: '3.9'
            tox_env: 'py39-test-astropy3'
          - os: ubuntu-latest
            python: '3.10'
            tox_env: 'py310-test-astropy4'
          - os: ubuntu-latest
            python: '3.10'
            tox_env: 'py310-test-astropy5'
          - os: ubuntu-latest
            python: '3.10'
            tox_env: 'build_docs'

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Check out that no sensitive environment variable is shared
      run: env
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Install system dependencies
      if: "endsWith(matrix.tox_env, 'build_docs')"
      run: sudo apt-get -y install graphviz pandoc
    - name: Print Python, pip, setuptools, and tox versions
      run: |
        python -c "import sys; print(f'Python {sys.version}')"
        python -c "import pip; print(f'pip {pip.__version__}')"
        python -c "import setuptools; print(f'setuptools {setuptools.__version__}')"
        python -c "import tox; print(f'tox {tox.__version__}')"
    - name: Run tests
      if: "! matrix.use_remote_data"
      run: tox -e ${{ matrix.tox_env }}
    - name: Run tests with remote data
      if: "matrix.use_remote_data"
      run: tox -e ${{ matrix.tox_env }} -- --remote-data=any
    - name: Upload coverage to codecov
      if: "endsWith(matrix.tox_env, '-cov')"
      uses: codecov/codecov-action@v1.0.13
      with:
        file: ./coverage.xml
